### ISSUE TITLE
Rainbow checkbox doesn't work

### ISSUE THREAD

**Issue by danieleremin** [FlyTechVideos/BluescreenSimulator#64]
**_The rainbow checkbox does not seem to work_**. When it is checked the color of the fake bluescreen stays the same.

**Comment by iiRoco** [comment]
It's already fixed in the master branch.

**Comment by danieleremin** [comment]
When _exe_ is downloaded from the _release_ the problem persists. Please update the exe on the release.

**Comment by iiRoco** [comment]
There you go [v3.2](https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.2), use at your own risk.

**Comment by danieleremin** [comment]
Thank you. It now works.
